siaf/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include

import sistema.views
from siaf import settings

from . import views

urlpatterns = [
    path('', login_required(sistema.views.SistemaHome.as_view()), name="index"),
    path('admin/panel_administrativo', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('sistema/', include('sistema.urls')),
    path('proveedores/', include('proveedores.urls')),
    path('administrador/', include('administrador.urls')),
    path('tablero/', include('tablero.urls')),
    path('prensa/', include('prensa.urls')),
    path('sistema/declaracionJurada', views.enviarDeclaracionJurada, name="enviarDeclaracionJurada"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sistema/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('perfil', login_required(views.ProfileView.as_view()), name="userProfile"),
    path('logout_view', login_required(views.logout_view.as_view()), name="logout_view"),
    path('registrarse', views.registerUser, name="registrarUsuario"),

    path('recuperarContrasena', auth_views.PasswordResetView.as_view(template_name='registration/recPassword.html'), name="recuperarContrasena"),
    path('recuperarContrasenaEnviado', auth_views.PasswordResetDoneView.as_view(template_name='registration/recPasswordSend.html'), name="password_reset_done"),
    path('recuperarContrasenaReinicio/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/recPasswordReset.html'), name="password_reset_confirm"),
    path('recuperarContrasenaCompleto/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/recPasswordCompleted.html'), name="password_reset_complete"),


    path('', login_required(views.home.as_view()), name="home"),
    path('traerInfoProfile', login_required(views.traerInfoProfile), name="traerInfoProfile"),
    path('submitProfile', login_required(views.submitProfile), name="submitProfile"),
    path('validarEmailProfile', login_required(views.validarEmailProfile), name="validarEmailProfile"),
]

sistema/models.py
from django.contrib.auth.models import User, Group
from django.db import models

# Create your models here.

Group.add_to_class('home', models.CharField(max_length=150, null=True, blank=True, verbose_name="Home"))
Group.add_to_class('icon', models.CharField(max_length=150, null=True, blank=True, verbose_name="Icono"))

class Profile(models.Model):
    OPCIONES = (
        ('T', 'TITULAR'),
        ('R', 'RESPONSABLE'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=150, null=False, blank=True)
    nombreResponsable = models.CharField(max_length=150, null=False, blank=True)
    apellidoResponsable = models.CharField(max_length=150, null=False, blank=True)
    dni = models.BigIntegerField(null=True, default=None)
    direccion = models.CharField(max_length=150, null=False, blank=True)
    caracter = models.CharField(max_length=10, choices=OPCIONES)
    email = models.EmailField(null=False, blank=True)
    telefono = models.CharField(max_length=50, null=True, blank=True)
    observaciones = models.TextField(null=True, blank=True)
    foto = models.ImageField(null=True, blank=True, upload_to='sistema/profile_images')
    create_at = models.DateTimeField(auto_now_add=True)
    activate_at = models.DateTimeField(auto_now_add=False, null=True, blank=True)
    disabled_at = models.DateTimeField(auto_now_add=False, null=True, blank=True)
    def __str__(self):
        return self.user.username

    def to_json(self):
        return {
            'cuit': self.user.username,
            'rs' : self.nombre,
            'dni': self.dni,
            'caracter': self.caracter,
            'direccion': self.direccion,
            'email': self.email,
            'telefono': self.telefono,
            'nombreResponsable': self.nombreResponsable,
            'apellidoResponsable': self.apellidoResponsable
        }


class MenuGrupo(models.Model):
    grupo = models.ForeignKey(Group, verbose_name='Grupo', on_delete=models.CASCADE)
    url = models.CharField(max_length=150, null=True, blank=True, verbose_name="url")
    nombre = models.CharField(max_length=150, null=True, blank=True, verbose_name="nombre")
    orden = models.IntegerField(null=False, default=0)
    def __str__(self):
        return self.grupo.name + ' ' + self.nombre


class Ayuda(models.Model):
    grupo = models.ForeignKey(Group, verbose_name='Grupo', on_delete=models.CASCADE, null=True, blank=True)
    nombre = models.CharField(max_length=150, null=True, blank=True, verbose_name="nombre")
    descripcion = models.CharField(max_length=10000, null=True, blank=True, verbose_name="Descripción")
    url = models.CharField(max_length=150, null=True, blank=True, verbose_name="url")

    def __str__(self):
        return self.nombre

sistema/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db import models
import re


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class registroUsuario(forms.Form):

    OPCIONES = (
        ('T', 'TITULAR'),
        ('R', 'RESPONSABLE'),
    )

    username = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'placeholder': 'CUIL/CUIT',
        'autocomplete': 'off',
        'required': True,
        'class': 'form-control',
        'type': 'number'
    }))

    nombre = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'placeholder': 'Razón Social',
        'autocomplete': 'off',
        'required': True,
        'class': 'form-control'
    }))

    nombreResponsable = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'placeholder': 'Nombre Responsable',
        'autocomplete': 'off',
        'required': True,
        'class': 'form-control'
    }))

    apellidoResponsable = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'placeholder': 'Apellido Responsable',
        'autocomplete': 'off',
        'required': True,
        'class': 'form-control'
    }))

    dni = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'placeholder': 'DNI',
        'autocomplete': 'off',
        'required': True,
        'class': 'form-control',
        'type': 'number'
    }))

    caracter = forms.ChoiceField(choices=OPCIONES, widget=forms.Select(attrs={
        'placeholder': 'Carácter',
        'autocomplete': 'off',
        'required': True,
        'class': 'form-control',
    }))

    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'autocomplete': 'off',
        'placeholder': 'Mail',
        'required': True
    }))
    direccion = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'autocomplete': 'off',
        'placeholder': 'Dirección y C.P.',
        'required': True
    }))
    telefono = forms.IntegerField(required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'number',
        'autocomplete': 'off',
        'placeholder': 'Celular (Ej.: 3885044907)',
        'required': False,
        'max_length': 12,
        'min_length': 8,
        'onChange': 'controlarNumeroCel()'
    }))
    password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'autocomplete': 'off',
        'placeholder': 'Contraseña',
        'required': True
    }))
    password2 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'autocomplete': 'off',
        'placeholder': 'Repetir Contraseña',
        'required': True
    }))


    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('El número de CUIT ya se encuentra registrado.')
        return username

    def clean_email(self):
        correo = self.cleaned_data.get('email')
        if User.objects.filter(email=correo).exists():
         raise forms.ValidationError('El mail ya se encuentra registrado.')
        return correo

    def clean_password2(self):
            password = self.cleaned_data.get('password')
            password2 = self.cleaned_data.get('password2')

            if password != password2:
                raise forms.ValidationError('Las contraseñas no coinciden.')
            else:
                if validar_contrasena(password) and len(password) >= 8:
                    return password2
                else:
                    raise forms.ValidationError(
                        'La contraseña debe tener al menos 8 caracteres, al menos una mayúscula, una minúsculas, un número y un simbolo especial.')


def validar_contrasena(contrasena):
    # Verificar si la contraseña contiene al menos una letra mayúscula
    if not re.search(r'[A-Z]', contrasena):
        return False

    # Verificar si la contraseña contiene al menos una letra minúscula
    if not re.search(r'[a-z]', contrasena):
        return False

    # Verificar si la contraseña contiene al menos un número
    if not re.search(r'\d', contrasena):
        return False

    # Verificar si la contraseña contiene al menos un símbolo
    if not re.search(r'[\W_]', contrasena):
        return False

    # Verificar la longitud de la contraseña (opcional)
    if len(contrasena) < 8:
        return False

    return True


class editarPerfil(forms.Form):

        OPCIONES = (
            ('T', 'TITULAR'),
            ('R', 'RESPONSABLE'),
        )

        nombreResponsable = forms.CharField(required=True, label="Nombre Responsable", widget=forms.TextInput(attrs={
            'placeholder': '',
            'autocomplete': 'off',
            'required': True,
            'class': 'form-control'
        }))

        apellidoResponsable = forms.CharField(required=True, label="Apellido Responsable", widget=forms.TextInput(attrs={
            'placeholder': '',
            'autocomplete': 'off',
            'required': True,
            'class': 'form-control'
        }))

        dni = forms.CharField(required=True, label="DNI", widget=forms.TextInput(attrs={
            'placeholder': '',
            'autocomplete': 'off',
            'required': True,
            'class': 'form-control',
            'type': 'number'
        }))

        caracter = forms.ChoiceField(choices=OPCIONES, label="Carácter", widget=forms.Select(attrs={
            'placeholder': '',
            'autocomplete': 'off',
            'required': True,
            'class': 'form-control',
        }))

        email = forms.EmailField(required=True, label="Mail", widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'autocomplete': 'off',
            'placeholder': '',
            'required': True,
            'onChange': 'validaciónEmail(this.value)'
        }))

        direccion = forms.CharField(required=True, label="Dirección y C.P.", widget=forms.TextInput(attrs={
            'class': 'form-control',
            'autocomplete': 'off',
            'placeholder': '',
            'required': True
        }))

        telefono = forms.IntegerField(required=False, label="Celular (Ej.: 3885044907)", widget=forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'number',
            'autocomplete': 'off',
            'placeholder': '',
            'required': False,
            'max_length': 12,
            'min_length': 8,
            'onChange': 'controlarNumeroCel()'
        }))

        def clean_email(self):
            correo = self.cleaned_data.get('email')
            if User.objects.filter(email=correo).exists():
                raise forms.ValidationError('El mail ya se encuentra registrado.')
            return correo

templates/sistema/abm.html
{% extends "base.html" %}
{% block extraCss %}
{% endblock %}
{% block main %}
    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row">
                    <div class="col-lg-12 col-md-8 col-sm-12">
                        <h2><a href="javascript:void(0);" class="btn btn-xs btn-link btn-toggle-fullwidth">
                            <i class="fa fa-arrow-left"></i></a> {{ defensoria }}</h2>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/"><i class="icon-home"></i></a></li>
                            <li class="breadcrumb-item active">{{ titulo }}</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="body">
                            <div class="table-responsive">
                                <table id="data_table" class="table table-bordered table-striped table-hover small">
                                    <thead>
                                        <tr>
                                            {% for list in list_display %}
                                                <th>{{ list }}</th>
                                            {% endfor %}
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for values in objetos %}
                                            <tr>
                                            {% for value in values %}
                                                <td>
                                                {% if forloop.last %}
                                                    {% if 'editar' in botones %}
                                                        <button type="button" data-id="{{ value }}" class="btn btn-info js-editar" title="Editar"><i class="fa fa-edit"></i></button>
                                                    {% endif %}
                                                    {% if 'eliminar' in botones %}
                                                        <button type="button" data-id="{{ value }}" class="btn btn-danger js-sweetalert" title="Eliminar"><i class="fa fa-trash-o"></i></button>
                                                    {% endif %}
                                                {% else %}
                                                     {{ value }}
                                                {% endif %}
                                                </td>
                                            {% endfor %}
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="modal fade" id="modal-alta" tabindex="-1">
        <div class="modal-dialog modal-lg">
            <div class="modal-content"></div>
        </div>
    </div>

{% endblock %}
{% block extraJS %}
    <script>
    $(document).ready(function(){

        $.fn.dataTable.ext.buttons.nuevo = {
            text: 'Nuevo',
            className: 'btn-info',
            action: function ( e, dt, node, config ) {
                loadForm()
            }
        };

        var data_table = $('#data_table').DataTable( {
            autoWidth: false,
            dom: 'Bfrtip',
            buttons: [
                {% if 'insertar' in botones %}
                'nuevo',
                {% endif %}
                'csv', 'print',
            ],
            language: {
                url: "https://cdn.datatables.net/plug-ins/1.11.3/i18n/es_es.json"
            }
        } );


        var loadForm = function () {
            var btn = $(this);
            $.ajax({
              url: '{% url 'abmAlta' app_name=app_name model_name=model_name form_name=form_name %}',
              type: 'get',
                {% if padre  %}
                    data: {padre: '{{ padre }}',field_name: '{{ field_name }}',field_value: '{{ field_value }}'},
                {% endif %}
              dataType: 'json',
              beforeSend: function () {
                $("#modal-alta .modal-content").html("");
                $("#modal-alta").modal("show");
              },
              success: function (data) {
                $("#modal-alta .modal-content").html(data.html_form);
              }
            });
          };

        $(".js-editar").click(function(){
            var btn = $(this);
            $.ajax({
              url: '{% url 'abmAlta' app_name=app_name model_name=model_name form_name=form_name %}',
              type: 'get',
              data: {id: btn.attr("data-id")},
              dataType: 'json',
              beforeSend: function () {
                $("#modal-alta .modal-content").html("");
                $("#modal-alta").modal("show");
              },
              success: function (data) {
                $("#modal-alta .modal-content").html(data.html_form);
              }
            });

        });

        $(".js-sweetalert").click(function(){
            var btn = $(this);
           swal({
                title: "Esta seguro?",
                text: "Esta operacion no se puede deshacer!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#dc3545",
                confirmButtonText: "Si, Eliminar!",
                cancelButtonText: "Cancelar",
                closeOnConfirm: false
            }, function () {
                $.ajax({
                      url: '{% url 'abmEliminar' app_name=app_name model_name=model_name form_name=form_name %}',
                      type: 'get',
                      data: {id: btn.attr("data-id")},
                      dataType: 'json',
                      success: function (data) {
                          swal({
                               title: "Eliminado!",
                               text: "Se elimino exitosamente!",
                               type: "success"
                             },
                           function(){
                               location.reload();
                           }
                        );
                      }
                    });

            });
        });

    });
</script>
{% endblock %}

templates/sistema/abmAlta.html
<div class="modal-header">
    <h4 class="title" id="largeModalLabel">{{ titulo }}</h4>
</div>
<form id="form_alta" method="post" enctype="multipart/form-data">

    <div class="modal-body">
        {% csrf_token %}
        <input type="hidden" id="padre" name="padre" value="{{ padre }}">
        <input type="hidden" id="field_name" name="field_name" value="{{ field_name }}">
        <input type="hidden" id="field_value" name="field_value" value="{{ field_value }}">
        <input type="hidden" id="personaopera" name="personaopera" value="{{ personaopera }}">
        {% if form.instance.id %}
            <input type="hidden" id="id" name="id" value="{{ form.instance.id }}">
        {% endif %}
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12">
                {{ form.as_div }}
            </div>
        </div>

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <button type="button" id="btn-guardar" class="btn btn-primary">Guardar</button>
    </div>
</form>

<script>
    $(document).ready(function(){

        $("#btn-guardar").click(function(){
            var btn = $(this);
            //var formData = $("#form_alta").serializeArray();
            var formData = new FormData($('#form_alta')[0]);
            $.ajax({
              url: '{% url 'abmAlta' app_name=app_name model_name=model_name form_name=form_name %}',
              type: 'POST',
              data: formData,
              processData: false,
              contentType: false,
              success: function (data) {
                   if (data['resultado'] == "OK") {
                       swal({
                               title: "Ok!",
                               text: "Se guardo correctamente!",
                               type: "success"
                             },
                           function(){
                               location.reload();
                           }
                        );
                   } else {
                       swal({ type: "error", html:true, title: "Error!", text: data['resultado'] });

                   }
              }
            });

        });


    });
</script>

templates/sistema/home.html
{% extends "base.html" %}
{% block extraCss %}
{% endblock %}
{% block main %}
{% load static %}
<div id="main-content" class="profilepage_2 blog-page">
  <div class="container-fluid">
    <div class="block-header">
      <div class="row g-3">
        <div class="col-lg-5 col-md-8 col-sm-12">
          <h2><a href="javascript:void(0);" class="btn btn-xs btn-link btn-toggle-fullwidth"><i class="fa fa-arrow-left"></i></a>
            {{ titulo }}</h2>
            <ul class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'home' %}"><i class="icon-home"></i></a></li>
              <li class="breadcrumb-item active">{{ titulo }}</li>
            </ul>
          </div>
        </div>
      </div>

      <div class="row clearfix">
       <div class="col-lg-12 col-md-12">

        <div class="card">
          <div class="card-body">
            {% load static %}
            <div class="col-lg-12 text-center mt-5">
                <img width="500px" class="img-fluid" src="{% static 'assets/images/logo-azul.png' %}" alt="Logo">
            </div>
            <div class="col-lg-12 text-center mt-5 mb-5">
                <h1 class="">Bienvenido al Sistema de Proveedores del Estado.</h1>
            </div>
            <div class="col-lg-12 text-center mt-5 mb-5">
                <a class="h5 text-danger cursor-pointer" onclick="window.open('/static/documents/MANUAL.pdf', '_blank')">Clic aquí para descargar manual de usuarios <i class="fa fa-file-pdf-o"></i></a>
            </div>
          </div>
        </div>
      </div>
      </div>

    </div>
  </div>


  <!-- --------------------------------------------------------------------------------- -->
  <!-- --------------------------------------------------------------------------------- -->
  <!-- --------------------------------------------------------------------------------- -->


  {% endblock %}
  {% block extraJS %}
  <script>

  </script>
  {% endblock %}

templates/sistema/profile.html
{% extends "base.html" %}
{% block extraCss %}
{% endblock %}
{% block main %}
{% load static %}
<div id="main-content" class="profilepage_2 blog-page">
  <div class="container-fluid">
    <div class="block-header">
      <div class="row g-3">
        <div class="col-lg-5 col-md-8 col-sm-12">
          <h2><a href="javascript:void(0);" class="btn btn-xs btn-link btn-toggle-fullwidth"><i class="fa fa-arrow-left"></i></a> {{ titulo }}</h2>
          <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ index }}"><i class="icon-home"></i></a></li>
            <li class="breadcrumb-item active">{{ titulo }}</li>
          </ul>
        </div>
      </div>
    </div>

    <div class="row clearfix g-3">

      <div class="col-lg-12 col-md-12">
        <div class="card profile-header mb-3">
          <div class="body">

            <div class="row div-datos">
              <div class="col-sm-6 col-md-6 col-lg-2">
                <p class="fw-bold">CUIT/CUIL:</p>
              </div>
              <div class="col-sm-6 col-md-6 col-lg-10">
                <p id="lblUsername"></p>
              </div>
            </div>

            <div class="row div-datos">
              <div class="col-sm-6 col-md-6 col-lg-2">
                <p class="fw-bold">Razón Social:</p>
              </div>
              <div class="col-sm-6 col-md-6 col-lg-10">
                <p id="lblRS"></p>
              </div>
            </div>

            <div class="row div-datos">
              <div class="col-sm-6 col-md-6 col-lg-2">
                <p class="fw-bold">Nombre Responsable:</p>
              </div>
              <div class="col-sm-6 col-md-6 col-lg-10">
                <p id="lblNombreResponsable"></p>
              </div>
            </div>

            <div class="row div-datos">
              <div class="col-sm-6 col-md-6 col-lg-2">
                <p class="fw-bold">Apellido Responsable:</p>
              </div>
              <div class="col-sm-6 col-md-6 col-lg-10">
                <p id="lblApellidoResponsable"></p>
              </div>
            </div>

            <div class="row div-datos">
              <div class="col-sm-6 col-md-6 col-lg-2">
                <p class="fw-bold">DNI:</p>
              </div>
              <div class="col-sm-6 col-md-6 col-lg-10">
                <p id="lblDni"></p>
              </div>
            </div>

            <div class="row div-datos">
              <div class="col-sm-6 col-md-6 col-lg-2">
                <p class="fw-bold">Carácter:</p>
              </div>
              <div class="col-sm-6 col-md-6 col-lg-10">
                <p id="lblCaracter"></p>
              </div>
            </div>

            <div class="row div-datos">
              <div class="col-sm-6 col-md-6 col-lg-2">
                <p class="fw-bold">Mail:</p>
              </div>
              <div class="col-sm-6 col-md-6 col-lg-10">
                <p id="lblEmail"></p>
              </div>
            </div>

            <div class="row div-datos">
              <div class="col-sm-6 col-md-6 col-lg-2">
                <p class="fw-bold">Dirección/C.P.:</p>
              </div>
              <div class="col-sm-6 col-md-6 col-lg-10">
                <p id="lblDireccion"></p>
              </div>
            </div>

            <div class="row div-datos">
              <div class="col-sm-6 col-md-6 col-lg-2">
                <p class="fw-bold">Celular:</p>
              </div>
              <div class="col-sm-6 col-md-6 col-lg-10">
                <p id="lblTelefono"></p>
              </div>
            </div>

            <div class="row div-datos">
              <div class="col-sm-6 col-md-6 col-lg-2">
                <button onclick="abrirEditar()" class="btn btn-primary"><i class="fa fa-pencil"></i> Editar</button>
              </div>
            </div>


            <div class="row div-form" style="display: none">
              <div class="col-sm-12 col-md-12 col-lg-12">
                <p class="lead font-weight-bold mb-3">Modificar Datos</p>
              </div>
            </div>

            <form id="formProfile"  data-parsley-validate class="form-auth-small div-form" style="display: none">
              <div class="row" >

                {% csrf_token %}

                {% for m in form %}

                <div class="form-group col-lg-4 form-group mb-2">

                  <label>{{ m.label }}</label>
                  {{ m }}

                </div>


                {% endfor %}
              </div>
              <div class="row">
                <div class="col-sm-12 col-md-2 offset-md-4 col-lg-2 offset-lg-4">
                  <button type="submit" class="btn btn-primary w-100">Guardar</button>
                </div>
                <div class="col-sm-12 col-md-2 col-md-offset-2 col-lg-2 col-lg-offset-4">
                  <button type="button" id="btnCancelar" class="btn btn-primary w-100">Cancelar</button>
                </div>
              </div>
            </form>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}
{% block extraJS %}

<script>

function cargarInfo(){
  var valores = {
    "csrfmiddlewaretoken" : '{{csrf_token }}',
  }
  $.ajax({
    type: 'POST',
    url: "{% url 'traerInfoProfile' %}",
    data: valores,
    async: false,
    success: function(response) {

      $("#lblUsername").text(response.profile.cuit);
      $("#lblRS").text(response.profile.rs);

      $("#lblNombreResponsable").text(response.profile.nombreResponsable);
      $("#id_nombreResponsable").val(response.profile.nombreResponsable);

      $("#lblApellidoResponsable").text(response.profile.apellidoResponsable);
      $("#id_apellidoResponsable").val(response.profile.apellidoResponsable);

      $("#lblDni").text(response.profile.dni);
      $("#id_dni").val(response.profile.dni);

      $("#lblCaracter").text(response.profile.caracter == 'T' ? 'Titular' : 'Responsable');
      $("#id_caracter").val(response.profile.caracter)

      $("#lblEmail").text(response.profile.email);
      $("#id_email").val(response.profile.email);

      $("#lblDireccion").text(response.profile.direccion);
      $("#id_direccion").val(response.profile.direccion);

      $("#lblTelefono").text(response.profile.telefono);
      $("#id_telefono").val(response.profile.telefono);

      $('.div-datos').show(200);
      $(".div-form").hide(200);

    }
  });

}


function abrirEditar(){

  $("#formProfile").trigger("reset").parsley().reset();

  $("#id_nombreResponsable").val($("#lblNombreResponsable").text());
  $("#id_apellidoResponsable").val($("#lblApellidoResponsable").text());
  $("#id_dni").val($("#lblDni").text());
  $("#id_email").val($("#lblEmail").text());
  $("#id_direccion").val($("#lblDireccion").text());
  $("#id_telefono").val($("#lblTelefono").text());

  $('.div-datos').hide(200);
  $(".div-form").show(200);
}

$("#btnCancelar").click(function(){

    $('.div-datos').show(200);
    $(".div-form").hide(200);

});

$(document).ready(function(){

  $('#formProfile').parsley();
  cargarInfo();


});

$('#formProfile').on('submit', function(event) {

   event.preventDefault();

    var form = $(this);
    form.parsley().validate();

    if (form.parsley().isValid()) {

      $.ajax({
      type: 'POST',
      async: false,
      url: "{% url 'submitProfile' %}",
      data: $(this).serialize(),
      success: function(data) {

       cargarInfo();

       }
      });

    }

  });


  function validaciónEmail(correo){

     $.ajax({
      type: 'POST',
      async: false,
      url: "{% url 'validarEmailProfile' %}",
      data: {'csrfmiddlewaretoken' : '{{csrf_token }}', 'correo': correo},
      success: function(data) {

       if (data.status != 'OK'){
           swal("Atención!", "El mail ingresado se encuentra registrado en otro usuario.","warning")
           $("#id_email").val("");
       }

       }
      });

  }

</script>

{% endblock %}