siaf/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include

import sistema.views
from siaf import settings

from . import views

urlpatterns = [
    path('', login_required(sistema.views.SistemaHome.as_view()), name="index"),
    path('admin/panel_administrativo', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('sistema/', include('sistema.urls')),
    path('proveedores/', include('proveedores.urls')),
    path('administrador/', include('administrador.urls')),
    path('tablero/', include('tablero.urls')),
    path('prensa/', include('prensa.urls')),
    path('sistema/declaracionJurada', views.enviarDeclaracionJurada, name="enviarDeclaracionJurada"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sistema/models.py
from django.contrib.auth.models import User, Group
from django.db import models

# Create your models here.

Group.add_to_class('home', models.CharField(max_length=150, null=True, blank=True, verbose_name="Home"))
Group.add_to_class('icon', models.CharField(max_length=150, null=True, blank=True, verbose_name="Icono"))

class Profile(models.Model):
    OPCIONES = (
        ('T', 'TITULAR'),
        ('R', 'RESPONSABLE'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=150, null=False, blank=True)
    nombreResponsable = models.CharField(max_length=150, null=False, blank=True)
    apellidoResponsable = models.CharField(max_length=150, null=False, blank=True)
    dni = models.BigIntegerField(null=True, default=None)
    direccion = models.CharField(max_length=150, null=False, blank=True)
    caracter = models.CharField(max_length=10, choices=OPCIONES)
    email = models.EmailField(null=False, blank=True)
    telefono = models.CharField(max_length=50, null=True, blank=True)
    observaciones = models.TextField(null=True, blank=True)
    foto = models.ImageField(null=True, blank=True, upload_to='sistema/profile_images')
    create_at = models.DateTimeField(auto_now_add=True)
    activate_at = models.DateTimeField(auto_now_add=False, null=True, blank=True)
    disabled_at = models.DateTimeField(auto_now_add=False, null=True, blank=True)
    def __str__(self):
        return self.user.username

    def to_json(self):
        return {
            'cuit': self.user.username,
            'rs' : self.nombre,
            'dni': self.dni,
            'caracter': self.caracter,
            'direccion': self.direccion,
            'email': self.email,
            'telefono': self.telefono,
            'nombreResponsable': self.nombreResponsable,
            'apellidoResponsable': self.apellidoResponsable
        }


class MenuGrupo(models.Model):
    grupo = models.ForeignKey(Group, verbose_name='Grupo', on_delete=models.CASCADE)
    url = models.CharField(max_length=150, null=True, blank=True, verbose_name="url")
    nombre = models.CharField(max_length=150, null=True, blank=True, verbose_name="nombre")
    orden = models.IntegerField(null=False, default=0)
    def __str__(self):
        return self.grupo.name + ' ' + self.nombre


class Ayuda(models.Model):
    grupo = models.ForeignKey(Group, verbose_name='Grupo', on_delete=models.CASCADE, null=True, blank=True)
    nombre = models.CharField(max_length=150, null=True, blank=True, verbose_name="nombre")
    descripcion = models.CharField(max_length=10000, null=True, blank=True, verbose_name="Descripción")
    url = models.CharField(max_length=150, null=True, blank=True, verbose_name="url")

    def __str__(self):
        return self.nombre

templates/base.html
{% load static %}
<!doctype html>
<html lang="es">

<head>
<title>SISTEMA INTEGRADO DE ADMINISTRACIÓN FINANCIERA</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

<link rel="icon" href="{% static 'assets/images/favicon.ico' %}" type="image/x-icon">

<!-- VENDOR CSS -->
<link rel="stylesheet" href="{% static 'assets/css/dataTables.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/vendor/nouislider/nouislider.min.css' %}" />

<!-- SELECT2  -->
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" />


<link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.3.6/css/buttons.dataTables.min.css">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.14.0-beta2/css/bootstrap-select.min.css">


<!-- MAIN CSS -->
<link rel="stylesheet" href="{% static 'assets/css/main.css' %}">

<link rel="stylesheet" href="{% static 'assets/vendor/sweetalert/sweetalert.css' %}"/>
<script src="{% static 'assets/vendor/sweetalert/sweetalert.min.js' %}"></script>

<link rel="stylesheet" href="{% static 'assets/vendor/parsleyjs/css/parsley.css' %}">

<!-- EXTRA CSS -->
{% block extraCss %}

{% endblock %}

</head>
<body data-theme="theme-purple">

<!-- Overlay For Sidebars -->

<div id="wrapper">

    <nav class="navbar navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-btn">
                <button type="button" class="btn-toggle-offcanvas text-light"><i class="lnr lnr-menu fa fa-bars"></i></button>
            </div>

            <div class="navbar-brand">
                <a href="{{ index }}">
                    <img class="img-fluid" src="{% static 'assets/images/logo-blanco.png' %}" alt="Logo">
                </a>                
            </div>
            
            <div class="navbar-right">
                <div id="navbar-menu">
                    {% include "navbar.html" %}
                </div>
            </div>
        </div>
    </nav>

    <div id="left-sidebar" class="sidebar">
        <div class="sidebar-scroll">
            <div class="user-account">
                <img src="{% if user.profile.foto %}{{ user.profile.foto.url }}{% else %} {% static 'assets/images/user.png' %} {% endif %}" class="rounded-circle user-photo" alt="User Profile Picture">
                <div class="dropdown">
                    <span>Bienvenido,</span>
                    <span class="user-name"><strong>{{ user.get_full_name }}</strong></span>
                </div>
            </div>
            <!-- Nav tabs -->
            <ul class="nav nav-tabs">
                <li class="nav-item"><a class="nav-link active" data-bs-toggle="tab" href="#menu">Menu</a></li>
                <li class="nav-item" hidden><a class="nav-link" data-bs-toggle="tab" href="#question"><i class="icon-question"></i></a></li>
            </ul>
                
            <!-- Tab panes -->
            <div class="tab-content ps-0 pe-0">
                <div class="tab-pane active" id="menu">
                    {%  include 'menu.html' %}
                </div>
                <div class="tab-pane px-2" id="question" hidden>
                    {%  include 'menuAyuda.html' %}
                </div>                
            </div>          
        </div>
    </div>
    <!-- BLOQUE MAIN -->
    {% block main %}
    <div id="main-content">
        BLOQUE MAIN DEFAULT
    </div>
    {% endblock %}

    
</div>

<!-- Javascript -->
<script src="{% static 'assets/bundles/libscripts.bundle.js' %}"></script>
<script src="{% static 'assets/bundles/vendorscripts.bundle.js' %}"></script>
<script src="{% static 'assets/bundles/datatablescripts.bundle.js' %}"></script>
<script src="{% static 'assets/vendor/nouislider/nouislider.js' %}"></script> <!-- noUISlider Plugin Js -->
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="{% static 'assets/vendor/ckeditor/ckeditor.js' %}"></script> <!-- Ckeditor -->

<script src="{% static 'assets/bundles/mainscripts.bundle.js' %}"></script>

<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.3.6/js/dataTables.buttons.min.js"></script>


<script src="{% static 'assets/vendor/parsleyjs/js/parsley.min.js' %}"></script>


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>


<script>
$(document).ready(function(){
  $("#ul_input_ayuda").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#ul_ayuda li").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});

function controlPantalla(){
 var width = $(window).width() ;

 if (width<= 1201){
     $("body").removeClass('layout-fullwidth');
     $(".btn-toggle-fullwidth").hide();
 }else{
     $(".btn-toggle-fullwidth").show();
 }


}

window.addEventListener("resize", controlPantalla);
window.addEventListener("load", controlPantalla);

function formatearNumero(numero) {
            return numero.toFixed(2)  // Formatear a 2 decimales
                .replace('.', ',')    // Reemplazar el punto decimal por una coma
                .replace(/\B(?=(\d{3})+(?!\d))/g, '.');  // Añadir puntos como separadores de miles
        }

</script>


<!-- EXTRA JS -->
{% block extraJS %}
{% endblock %}

<button type="button" onclick="window.open('https://api.whatsapp.com/send?phone=+5493885044907&text=Hola!%20necesito%20ayuda!%20%F0%9F%91%8B', '_blank')" class="btn btn-success btn-lg btn-circle" id="btn-back-to-top" style="display: block;">
    <center><i class="fa fa-whatsapp"></i></center>
  </button>


</body>
</html>

templates/menu.html
<nav id="left-sidebar-nav" class="sidebar-nav">
    <ul id="main-menu" class="metismenu">
        {% for grupo in user.groups.all %}
        <li class="active">
            <a href="#" class="has-arrow"><i class="{{ grupo.icon }}"></i> <span>{{ grupo }}</span></a>
            <ul class="collapse in">
                {% for menu in grupo.menugrupo_set.all|dictsort:"orden" %}
                    {%  if menu.grupo.id == 4 %}

                        {% if menu.nombre == 'Auditoría' %}
                           {% if 'prensa.admin_prensa' in user.get_all_permissions %}
                            <li><a href="{{ menu.url }}">{{ menu.nombre }}</a></li>
                           {% endif %}
                        {% else %}

                            <li><a href="{{ menu.url }}">{{ menu.nombre }}</a></li>

                        {% endif %}

                    {% else %}

                        <li><a href="{{ menu.url }}">{{ menu.nombre }}</a></li>

                    {% endif %}



                {% endfor %}
            </ul>
        </li>
        {% endfor %}
    </ul>
</nav>

templates/menuAyuda.html
    <div class="input-group">
        <span class="input-group-text"><i class="icon-magnifier"></i></span>
        <input type="text" class="form-control" placeholder="Buscar..." id="ul_input_ayuda">
    </div>

<ul class="list-unstyled question" id="ul_ayuda">
    <li class="menu-heading">GENERAL</li>
    {% for ayuda in ayuda_items %}
            <li><a href="{{ ayuda.url }}" target="_blank">{{ ayuda.nombre }}</a></li>
    {% endfor %}
    {% for grupo in user.groups.all %}
        <li class="menu-heading">{{ grupo }}</li>
        {% for ayuda in grupo.ayuda_set.all %}
            <li><a href="{{ ayuda.url }}" target="_blank">{{ ayuda.nombre }}</a></li>
        {% endfor %}
    {% endfor %}
</ul>

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<ul class="nav navbar-nav">
    <li class="dropdown">
{#        <a href="javascript:void(0);" class="dropdown-toggle icon-menu" data-bs-toggle="dropdown">#}
{#            <i class="icon-bell text-light"></i>#}
{#            <span class="notification-dot" style="background-color: white"></span>#}
{#        </a>#}
        <ul class="dropdown-menu notifications">
            <!--
            <li class="header"><strong>You have 4 new Notifications</strong></li>
            <li>
                <a href="javascript:void(0);">
                    <div class="media d-flex">
                        <div class="media-left">
                            <i class="icon-info text-warning"></i>
                        </div>
                        <div class="media-body">
                            <p class="text">Campaign <strong>Holiday Sale</strong> is nearly reach budget limit.</p>
                            <span class="timestamp">10:00 AM Today</span>
                        </div>
                    </div>
                </a>
            </li>
            <li>
                <a href="javascript:void(0);">
                    <div class="media d-flex">
                        <div class="media-left">
                            <i class="icon-like text-success"></i>
                        </div>
                        <div class="media-body">
                            <p class="text">Your New Campaign <strong>Holiday Sale</strong> is approved.</p>
                            <span class="timestamp">11:30 AM Today</span>
                        </div>
                    </div>
                </a>
            </li>
             <li>
                <a href="javascript:void(0);">
                    <div class="media d-flex">
                        <div class="media-left">
                            <i class="icon-pie-chart text-info"></i>
                        </div>
                        <div class="media-body">
                            <p class="text">Website visits from Twitter is 27% higher than last week.</p>
                            <span class="timestamp">04:00 PM Today</span>
                        </div>
                    </div>
                </a>
            </li>
            <li>
                <a href="javascript:void(0);">
                    <div class="media d-flex">
                        <div class="media-left">
                            <i class="icon-info text-danger"></i>
                        </div>
                        <div class="media-body">
                            <p class="text">Error on website analytics configurations</p>
                            <span class="timestamp">Yesterday</span>
                        </div>
                    </div>
                </a>
            </li>
            <li class="footer"><a href="javascript:void(0);" class="more">See all notifications</a></li>
            -->
        </ul>
    </li>
    <li class="dropdown">
        <a href="javascript:void(0);" class="dropdown-toggle icon-menu" data-bs-toggle="dropdown"><i class="icon-equalizer text-light"></i></a>
        <ul class="dropdown-menu user-menu menu-icon">
            <li class="menu-heading">Mi Cuenta</li>
            <li><a href="{% url 'userProfile' %}"><i class="icon-user"></i> <span>Mis Datos</span></a></li>
        </ul>
    </li>
    <li>
        <a href="{% url 'logout_view' %}" class="icon-menu"><i class="icon-login text-light"></i></a>
    </li>
</ul>

templates/password_reset_email.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Recuperación de contraseña</title>
</head>
<body>
    <p>Hola {{ user.username }},</p>
    <p>Has solicitado un restablecimiento de contraseña para tu cuenta en nuestro sitio web. Para restablecer tu contraseña, haz clic en el siguiente enlace:</p>
    <p><a href="{{ protocol }}://{{ domain }}{% url 'recuperarContrasenaReinicio' uidb64=uid token=token %}">Restablecer contraseña</a></p>
    <p>Si no solicitaste este restablecimiento, puedes ignorar este correo electrónico y tu contraseña seguirá siendo la misma.</p>
    <p>Atentamente,<br>{{ site_name }}</p>
</body>
</html>